name: Docker build

on:
  workflow_run:
    workflows: ["Maven build"]
    types:
      - completed

env:
  IMAGE_NAME: "$REGISTRY_HOST/L-Usine-Logicielle/moodle-grades-master_backend:dev"

jobs:
  docker:
    name: Docker build backend
    runs-on: self-hosted

    needs: [build]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: moodle-grades-master.jar
        path: backend/target

    - name: Create Docker image
      run: |
        cd backend
        docker build --no-cache -t "$REGISTRY_HOST/L-Usine-Logicielle/moodle-grades-master_backend:dev" .

  push_to_registry:
    name: Push to registry
    runs-on: self-hosted

    needs: [docker]

    steps:
    - name: Log in to registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: $REGISTRY_HOST
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to registry
      run: |
        cd backend
        docker push "$REGISTRY_HOST/L-Usine-Logicielle/moodle-grades-master_backend:dev"