name: Maven Verify

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Klint
      run: |
        cd backend
        mvn verify -Dmaven.test.skip=true