name: Lint

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  lint:
    name: Klint
    runs-on: self-hosted
    # continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Klint
      run: |
        cd backend
        mvn verify -Dmaven.test.skip=true