name: Maven Verify

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  lint:
    name: Klint
    runs-on: self-hosted
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Klint
      run: |
        cd backend
        mvn verify -Dmaven.test.skip=true

  build:
    name: Maven build
    runs-on: self-hosted

    needs: [lint]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build jar
      run: |
        cd backend
        mvn clean package -Dmaven.test.skip=true

    - run: mkdir -p target/

    - uses: actions/upload-artifact@v3
      with:
        name: moodle-grades-master.jar
        path: target/*.jar
  
  docker:
    name: Docker build
    runs-on: self-hosted

    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Create Docker image
      run: |
        cd backend
        docker build --no-cache -t moodle-master:dev .