name: Workflow CI/CD - Devel

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  lint:
    name: Klint
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Klint
      run: |
        cd backend
        chmod +x ./mvnw
        ./mvnw verify

  test:
    name: JUnit
    runs-on: self-hosted
    # continue-on-error: true
    
    permissions:
      contents: read
      checks: write
      id-token: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: JUnit Tests
      run: |
        cd backend
        chmod +x ./mvnw
        ./mvnw test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        report_paths: 'backend/target/surefire-reports/TEST-*.xml'

  build_backend:
    name: Maven build
    runs-on: self-hosted

    needs:
      - lint
      - test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build jar
      run: |
        cd backend
        chmod +x ./mvnw
        ./mvnw clean package