name: Workflow Backend

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  lint:
    name: Klint
    runs-on: self-hosted
    # continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Klint
      run: |
        cd backend
        mvn verify -Dmaven.test.skip=true

  build:
    name: Maven build
    runs-on: self-hosted

    needs: [lint]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build jar
      run: |
        cd backend
        mvn clean package -Dmaven.test.skip=true
        mkdir -p target/

    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: moodle-grades-master.jar
        path: backend/target/*.jar
        if-no-files-found: error
  
  docker:
    name: Docker build backend
    runs-on: self-hosted

    needs: [build]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: moodle-grades-master.jar
        path: backend/target

    - name: Create Docker image
      run: |
        cd backend
        docker build --no-cache -t "$REGISTRY_HOST/L-Usine-Logicielle/moodle-grades-master_backend:dev" .

  push_to_registry:
    name: Push to registry
    runs-on: self-hosted

    needs: [docker]

    steps:
    - name: Log in to registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: $REGISTRY_HOST
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to registry
      run: |
        cd backend
        docker push "$REGISTRY_HOST/L-Usine-Logicielle/moodle-grades-master_backend:dev"